name: Support Message / Thank You
description: Leave your name, choose projects you supported, and add a thank you message.
title: "Thank you from [Your Name]"
labels: support, thank-you
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Please enter your name or nickname.
      placeholder: Your name here
    validations:
      required: true

  - type: checkboxes
    id: projects
    attributes:
      label: Which projects did you support?
      options:
        - label: CrapFixer
        - label: Flyby11
        - label: Just a Coffee
        - label: Other 
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Message
      description: You can edit or add your thank you message below.
      placeholder: Write your personal thank you message here.
    validations:
      required: true
