name: Support Message / Thank You
description: |
  # Thank You for Your Support!

  Please leave your name and a short message below. Your support is greatly appreciated!

  ---

  Thank you for supporting this project!
title: "Thank you from [Your Name]"
labels: support, thank-you
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Please enter your name or nickname.
      placeholder: Your name here
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Message
      description: Write your thank you message or any personal note.
      placeholder: Thank you for this project!
    validations:
      required: true
